# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/arch_labs_2021/lab6/Exp6/Exp6.runs/synth_1/.Xil/Vivado-15568-DESKTOP-FTNKO2C/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7k325tffg676-2L
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    E:/arch_labs_2021/lab6/Exp6/code/core
    E:/arch_labs_2021/lab6/Exp6/code/auxillary
  } {
      E:/arch_labs_2021/lab6/Exp6/Exp6.runs/synth_1/.Xil/Vivado-15568-DESKTOP-FTNKO2C/realtime/multiplier_stub.v
      E:/arch_labs_2021/lab6/Exp6/Exp6.runs/synth_1/.Xil/Vivado-15568-DESKTOP-FTNKO2C/realtime/divider_stub.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/Code2Inst.v
      E:/arch_labs_2021/lab6/Exp6/code/core/CtrlUnit.v
      E:/arch_labs_2021/lab6/Exp6/code/core/FU_ALU.v
      E:/arch_labs_2021/lab6/Exp6/code/core/FU_div.v
      E:/arch_labs_2021/lab6/Exp6/code/core/FU_jump.v
      E:/arch_labs_2021/lab6/Exp6/code/core/FU_mem.v
      E:/arch_labs_2021/lab6/Exp6/code/core/FU_mul.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/Font816.v
      E:/arch_labs_2021/lab6/Exp6/code/core/ImmGen.v
      E:/arch_labs_2021/lab6/Exp6/code/common/MUX2T1_32.v
      E:/arch_labs_2021/lab6/Exp6/code/common/MUX8T1_32.v
      E:/arch_labs_2021/lab6/Exp6/code/core/RAM_B.v
      E:/arch_labs_2021/lab6/Exp6/code/common/REG32.v
      E:/arch_labs_2021/lab6/Exp6/code/core/REG_IF_IS.v
      E:/arch_labs_2021/lab6/Exp6/code/core/ROM_D.v
      E:/arch_labs_2021/lab6/Exp6/code/core/RV32core.v
      E:/arch_labs_2021/lab6/Exp6/code/core/Regs.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/VGATEST.v
      E:/arch_labs_2021/lab6/Exp6/code/common/add_32.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/btn_scan.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/clk_diff.v
      E:/arch_labs_2021/lab6/Exp6/code/common/cmp_32.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/debug_clk.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/display.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/my_clk_gen.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/parallel2serial.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/vga.v
      E:/arch_labs_2021/lab6/Exp6/code/auxillary/top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList E:/arch_labs_2021/lab6/Exp6/Exp6.runs/synth_1/.Xil/Vivado-15568-DESKTOP-FTNKO2C/realtime/top_synth.xdc
    rt::sdcChecksum
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {E:/arch_labs_2021/lab6/Exp6/Exp6.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/arch_labs_2021/lab6/Exp6/Exp6.runs/synth_1/.Xil/Vivado-15568-DESKTOP-FTNKO2C/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
