# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/arch_labs_2021/lab6/Exp6/Exp6.srcs/sources_1/ip/multiplier_1/multiplier.xci
# IP: The module: 'multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/arch_labs_2021/lab6/Exp6/Exp6.srcs/sources_1/ip/multiplier_1/multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/arch_labs_2021/lab6/Exp6/Exp6.srcs/sources_1/ip/multiplier_1/multiplier.xci
# IP: The module: 'multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/arch_labs_2021/lab6/Exp6/Exp6.srcs/sources_1/ip/multiplier_1/multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
